language: node_js
dist: xenial
node_js:
  # Use Node.js >= 12.x since we got problems with exceeding the default 1400MB
  # memory limit in Node.js 10 during webpack builds.
  # See also https://developer.ibm.com/articles/nodejs-memory-management-in-container-environments/
  - "12.15.0"
sudo: required

services:
  - docker
  - xvfb

cache:
  directories:
    # See .modulesFolders in node_modules/.yarn-integrity for the list of directories to cache
    - node_modules
    - packages/bierzo-wallet/node_modules
    - packages/sanes-browser-extension/node_modules
    - packages/sil-governance/node_modules
    - packages/valdueza-storybook/node_modules

before_install:
  # Enable user namespace cloning
  - "sudo sysctl -w kernel.unprivileged_userns_clone=1"

# Override default install step (travis.sh takes care of that)
install: true

before_script:
  # Make variables and function from Travis available in our script
  # See implementation https://github.com/travis-ci/travis-build/blob/4041ba116ddb3bdfd66ab8acbb7094dee28d6797/lib/travis/build/templates/header.sh
  # and http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
  - export ANSI_CLEAR
  - export -f travis_nanoseconds travis_fold travis_time_start travis_time_finish

script:
  - ./scripts/travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - /^milestone\/.+$/
    # Minor version branches: 0.9, 0.10, 1.2 etc.
    - /^[0-9]+\.[0-9]+$/
    # Tag builds: v0.9.1, v1.2.3-alpha456+build789 etc.
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

notifications:
  email: false
